### ISSUE TITLE
Cannot verify access_token

### ISSUE THREAD

**Issue by rock288** [ImJustLucas/hi-elysia#1]
![image](https://github.com/ImJustLucas/bun-elysia-boilerplate/assets/40531957/8d357e26-b5e0-4a03-bf8b-3a7444c455a5)

Please check help me. I tried checking but couldn't find where the error was

**Comment by ImJustLucas** [comment]
Hi @rock288 ! thanks for your issue !

Yes, I know about this jwt problem. It's been 6 months now that I can't solve it, if you ever feel like it, you can propose a pull request if you manage to solve this bug, I'd be eternally grateful.

This project is open source 🤍

**Comment by rock288** [comment]
Hi @ImJustLucas, nice repo!
 I will find a way to fix that error

**Comment by ImJustLucas** [comment]
Basically, it was a school project, carried out last October, it's possible that versions (such as elysia's) will be outated.

I hope you'll be able to find the problem, it's a pleasure working with you!

**Comment by rock288** [comment]
Hi @ImJustLucas I don't have permission to push a branch to your repository.
I see that this bug was fixed by adding the current time to the exp of the JWT.
`    exp: 30 * 24 * 60 * 60 + Date.now(),
`
Can you fix it for me, please?
Thank you!

**Comment by ImJustLucas** [comment]
Let's make a proper workflow, like a real open source project! like a branch ect.

You cannot create a branch and then add a PR?

**Comment by rock288** [comment]
![image](https://github.com/ImJustLucas/bun-elysia-boilerplate/assets/40531957/07f67550-c299-4375-8591-db35c001b25d)
I don't have permission to push a branch to your repository.

**Comment by ImJustLucas** [comment]
Indeed, I'm going to fix that then, I'll take the opportunity to up the dependencies, 

I'll add you as a co-author!

**Comment by rock288** [comment]
`I'll add you as a co-author!`
Please let me know when you have finished it.

**Comment by ImJustLucas** [comment]
mmmh it seems that the Date.now() doesn't fix the problem, i still have the return at line 25 
`const jwt = await jwtAccess.verify(cookie!.access_token);`, in the authentification.guard

and i need your email to add you on co-author (you can add me on discord if you want `imjustlucas`

**Comment by ImJustLucas** [comment]
OMG I FOUND IT

**Comment by rock288** [comment]
Hi @ImJustLucas 
My email: tuan2887903@gmail.com
